### ISSUE TITLE
Suggest updating readme to reference requirements.txt

### ISSUE THREAD

**Issue by oaustegard** [justinwkUKM/AskYourDocumentWithStreamlitChat#2]
Great little project!

I started with a new venv and then started pip installing as per the README, only to of course have a lot more missing modules than streamlit, streamlit-chat and openai...

Suggest updating the README to reference the requirements.txt instead

Thanks!

**Comment by justinwkUKM** [comment]
Thanks, thats a great suggestion. I will make those updates.
 
 pip install -r requirements.txt is what you needed.
