### ISSUE TITLE
Feature request: handle removal of documents

### ISSUE THREAD

**Issue by oaustegard** [justinwkUKM/AskYourDocumentWithStreamlitChat#3]
How do you handle running this with a new (set of) document(s)?  How do you avoid any removed document sticking around in the FAISS index, etc?

**Comment by justinwkUKM** [comment]
I put this thing up very quickly just for experimentation purpose. Thank you for your interest. With streamlit framework, the page is refreshed on every file upload and removal function. The index is recreated as you add new document or remove a document. However this is very inefficient. I will definitely work on improving this workflow in a couple of days and share the progress with you.

**Comment by justinwkUKM** [comment]
I may change FAISS in memory vector store with something more concrete soon such as Chroma or Pinecone.

For now as you remove and upload a new doc, it would not keep track of the context.

<img width="751" alt="Screen Shot 2023-05-10 at 3 29 44 AM" src="https://github.com/justinwkUKM/AskYourDocumentWithStreamlitChat/assets/20006026/8d8ca8c0-c5a6-4f52-bdcb-53cd98a0c35c">
